### ISSUE TITLE
Mesuare capacitance

### ISSUE THREAD

**Issue by Mewiss** [arminbw/wiretouch#2]
Hi! I'm making a simple touch screen and I'm having problems with connections to measure capacitance. Do you have any full schematic or diagram about this part.

Thanks!

**Comment by arminbw** [comment]
Hi! Which connections exactly are troubling you?

**Comment by Mewiss** [comment]
I dont' understand how you connect electrodes with sensor board

**Comment by arminbw** [comment]
We connected our sensor panel directly to the sensor board using 2.54mm pin headers. Of course you can use whatever connection you want. Just keep in mind that long cables might diminish the signal quality.
